# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Documents/FSE/GUI/MR3/ui/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.exit_btn = QtWidgets.QPushButton(self.centralWidget)
        self.exit_btn.setGeometry(QtCore.QRect(1760, 10, 141, 41))
        self.exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_btn.setObjectName("exit_btn")
        self.backgroud_label = QtWidgets.QLabel(self.centralWidget)
        self.backgroud_label.setEnabled(True)
        self.backgroud_label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backgroud_label.sizePolicy().hasHeightForWidth())
        self.backgroud_label.setSizePolicy(sizePolicy)
        self.backgroud_label.setSizeIncrement(QtCore.QSize(200, 200))
        self.backgroud_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.backgroud_label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.backgroud_label.setAutoFillBackground(True)
        self.backgroud_label.setFrameShape(QtWidgets.QFrame.Box)
        self.backgroud_label.setText("")
        self.backgroud_label.setTextFormat(QtCore.Qt.AutoText)
        self.backgroud_label.setPixmap(QtGui.QPixmap("../Background.jpg"))
        self.backgroud_label.setScaledContents(True)
        self.backgroud_label.setAlignment(QtCore.Qt.AlignCenter)
        self.backgroud_label.setWordWrap(False)
        self.backgroud_label.setObjectName("backgroud_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 689, 1901, 381))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.musicLayout = QtWidgets.QVBoxLayout()
        self.musicLayout.setObjectName("musicLayout")
        self.m_local_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.m_local_btn.setObjectName("m_local_btn")
        self.musicLayout.addWidget(self.m_local_btn)
        self.m_usb_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.m_usb_btn.setObjectName("m_usb_btn")
        self.musicLayout.addWidget(self.m_usb_btn)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.music_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.music_label.sizePolicy().hasHeightForWidth())
        self.music_label.setSizePolicy(sizePolicy)
        self.music_label.setMaximumSize(QtCore.QSize(150, 150))
        self.music_label.setAutoFillBackground(False)
        self.music_label.setText("")
        self.music_label.setPixmap(QtGui.QPixmap("../music.png"))
        self.music_label.setScaledContents(True)
        self.music_label.setAlignment(QtCore.Qt.AlignCenter)
        self.music_label.setObjectName("music_label")
        self.horizontalLayout_5.addWidget(self.music_label)
        self.musicLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.musicLayout)
        self.foto_Layout = QtWidgets.QVBoxLayout()
        self.foto_Layout.setObjectName("foto_Layout")
        self.f_local_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.f_local_btn.setAutoFillBackground(False)
        self.f_local_btn.setAutoDefault(False)
        self.f_local_btn.setDefault(False)
        self.f_local_btn.setFlat(False)
        self.f_local_btn.setObjectName("f_local_btn")
        self.foto_Layout.addWidget(self.f_local_btn)
        self.f_usb_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.f_usb_btn.setObjectName("f_usb_btn")
        self.foto_Layout.addWidget(self.f_usb_btn)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.foto_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foto_label.sizePolicy().hasHeightForWidth())
        self.foto_label.setSizePolicy(sizePolicy)
        self.foto_label.setMaximumSize(QtCore.QSize(150, 150))
        self.foto_label.setText("")
        self.foto_label.setPixmap(QtGui.QPixmap("../foto.png"))
        self.foto_label.setScaledContents(True)
        self.foto_label.setAlignment(QtCore.Qt.AlignCenter)
        self.foto_label.setObjectName("foto_label")
        self.horizontalLayout_4.addWidget(self.foto_label)
        self.foto_Layout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.foto_Layout)
        self.video_Layout = QtWidgets.QVBoxLayout()
        self.video_Layout.setObjectName("video_Layout")
        self.v_local_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.v_local_btn.setObjectName("v_local_btn")
        self.video_Layout.addWidget(self.v_local_btn)
        self.v_usb_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.v_usb_btn.setObjectName("v_usb_btn")
        self.video_Layout.addWidget(self.v_usb_btn)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.video_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.video_label.setMaximumSize(QtCore.QSize(150, 150))
        self.video_label.setText("")
        self.video_label.setPixmap(QtGui.QPixmap("../video.png"))
        self.video_label.setScaledContents(True)
        self.video_label.setAlignment(QtCore.Qt.AlignCenter)
        self.video_label.setObjectName("video_label")
        self.horizontalLayout_3.addWidget(self.video_label)
        self.video_Layout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.video_Layout)
        self.internet_Layout = QtWidgets.QVBoxLayout()
        self.internet_Layout.setObjectName("internet_Layout")
        self.netlfix_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.netlfix_btn.setObjectName("netlfix_btn")
        self.internet_Layout.addWidget(self.netlfix_btn)
        self.spotify_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.spotify_btn.setObjectName("spotify_btn")
        self.internet_Layout.addWidget(self.spotify_btn)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.internet_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.internet_label.sizePolicy().hasHeightForWidth())
        self.internet_label.setSizePolicy(sizePolicy)
        self.internet_label.setMaximumSize(QtCore.QSize(150, 150))
        self.internet_label.setText("")
        self.internet_label.setPixmap(QtGui.QPixmap("../web.png"))
        self.internet_label.setScaledContents(True)
        self.internet_label.setAlignment(QtCore.Qt.AlignCenter)
        self.internet_label.setObjectName("internet_label")
        self.horizontalLayout_2.addWidget(self.internet_label)
        self.internet_Layout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.internet_Layout)
        self.backgroud_label.raise_()
        self.exit_btn.raise_()
        self.horizontalLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exit_btn.setText(_translate("MainWindow", "EXIT"))
        self.m_local_btn.setText(_translate("MainWindow", "Local"))
        self.m_usb_btn.setText(_translate("MainWindow", "USB"))
        self.f_local_btn.setText(_translate("MainWindow", "Local"))
        self.f_usb_btn.setText(_translate("MainWindow", "USB"))
        self.v_local_btn.setText(_translate("MainWindow", "Local"))
        self.v_usb_btn.setText(_translate("MainWindow", "USB"))
        self.netlfix_btn.setText(_translate("MainWindow", "Netflix"))
        self.spotify_btn.setText(_translate("MainWindow", "Spotify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

